services:
  spotify-ws:
    image: ghcr.io/skidoodle/spotify-ws:main
    container_name: spotify-ws
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      #- LOG_LEVEL=DEBUG
      # ALLOWED_ORIGINS=http://localhost:3000
      # SERVER_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
