services:
  spotify-ws:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-ws
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      #- LOG_LEVEL=DEBUG
      #- ALLOWED_ORIGINS=http://localhost:3000
      #- SERVER_PORT=3000
